### ISSUE TITLE
Reach labeling does not respect the styling rule active state

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#136]
If horizontal positioning is uncompleted when adding a new reach, that reach cannot be seen afterwards.

**Comment by tudorbarascu** [comment]
I noticed that:
* horizontal_positioning column for od_reach can have NULL values
* the styling has `.. AND horizontal_positioning <> 5378` or `horizontal_positioning = 5378`, neglecting NULL columns.

As I believe this was not intended, I will make a pull request so that NULLs are take into consideration, e.g. `(horizontal_positioning <> 5378` or horizontal_positioning IS NULL)`

**Comment by andreasneumann** [comment]
I think it would be better to make horizontal_positioning a NOT NULL column. If you don't know the value, you can still use "unknown", which should be used by the symbology rule.

But we can use an ELSE symbology rule to display objects in a bright pink color to indicate that some necessary attribute is missing.

**Comment by tudorbarascu** [comment]
I thought about the non null column, but I settled on the Desktop side meanwhile.
This is also the case for function_hierarchic.
An ELSE symbology would be nice, do you want to do it or should I make a pull request?

**Comment by andreasneumann** [comment]
You can do it if you want.

Note that the rule system is currently broken in master (see https://hub.qgis.org/issues/13218) - so either you wait with the ELSE rule until it is fixed or you use the 2.10 version.

**Comment by tudorbarascu** [comment]
Thanks for the info, I will wait for the fix for now.

**Comment by tudorbarascu** [comment]
The fix is done thanks to Matthias.
Playing around with the ELSE rule I realized it may not be the best fit for our case:
* as the current styling renders all the features only at scales bigger than 1:2001, the ELSE rule needs to also have the same scale limit;
this is because the rules at scales bigger that 1:2001 are not presenting all the reaches by default and ELSE --> features are incorrectly presented as having missing values
* even though we restrict the ELSE rule by scale, If the user wants to turn off the visibility of some reaches, e.g. `Wide reaches, accurate positioning`, those features get rendered with the ELSE rule, which I think is wrong.

As a simple solution, I will simply make another rule: `function_hierarchic IS NULL or horizontal_positioning IS NULL` restricted to scale > 1:2001

@andreasneumann Opinions?

**Comment by m-kuhn** [comment]
I think it is fine to have the else rule only in place for > 1:2000.

It has been discussed before that the else rule should not match deactivated rules, so there is a chance that this gets fixed. But as an intermediate solution, IS NULL should be fine.

**Comment by tudorbarascu** [comment]
Solved in https://github.com/QGEP/QGEP/pull/145

**Comment by m-kuhn** [comment]
Else rules should be fixed soon
https://github.com/qgis/QGIS/pull/2286

**Comment by tudorbarascu** [comment]
ELSE rules should be avoided if layer uses labeling due to https://hub.qgis.org/issues/13631

**Comment by m-kuhn** [comment]
Maybe I do not understand the issue, but here it seems as if the labels do not respect the *active* checkbox at all, regardless of the presence of an ELSE rule.

**Comment by tudorbarascu** [comment]
When an ELSE rule is added (its checkbox disabled or not), all the labels are rendered without respecting the `active` checkbox, like in the following image:
![pic](https://cloud.githubusercontent.com/assets/3179646/10603170/294851aa-7725-11e5-95f7-7bb0620476c2.png)

The labels respect the active checkboxes only when the ELSE rule is not present.

![pic](https://cloud.githubusercontent.com/assets/3179646/10603251/aa1fc1fa-7725-11e5-9b10-eec2b3ba2343.png)

So, the ELSE rule presence influences the labels into not respecting active checkboxes.
I have tested with multiple rules on 2.8, 2.10 and master.

**Comment by andreasneumann** [comment]
Sounds like a bug that should be fixed in upstream QGIS

Can you open a bug report on http://hub.qgis.org/ - 

seems with your screenshots you can easily demonstrate the issue for a bug report.

**Comment by tudorbarascu** [comment]
I already filed the issue, it's https://hub.qgis.org/issues/13631 (also posted 4 comments above).
Have a nice day guys!

**Comment by m-kuhn** [comment]
I get totally unpredictable results with active/inactive rules and labels.

**In none of the following screenshots an ELSE rule has been involved**

All active (OK)
![abc](https://cloud.githubusercontent.com/assets/588407/10604051/32662e72-7722-11e5-9e69-a796a02c7563.png)

Some active
![abe](https://cloud.githubusercontent.com/assets/588407/10604049/323fdba0-7722-11e5-8f76-5bcbd842f460.png)

Some others active
![abd](https://cloud.githubusercontent.com/assets/588407/10604108/83cc9346-7722-11e5-89ed-e20ac0951c97.png)

**Comment by tudorbarascu** [comment]
@m-kuhn Indeed, I can replicate the problem without ELSE rules, but only in Master.

I cannot replicate it in QGIS 2.10 (except when using ELSE rule).

**Comment by andreasneumann** [comment]
hm - probably a side effect of the new label changes introduced by Martin Dobias? If you say it worked fine in QGIS 2.10 ...

If we want this to be fixed in the next release - we'd better act fast!

**Comment by tudorbarascu** [comment]
Opening the same qgep_en.qgs project, the same region, scale etc.. I can only replicate the problem in Master.

**Comment by andreasneumann** [comment]
I wonder if the labels are "at all" linked with the categories of the rest of the symbology?

In current master, Martin introduced rule-based labeling. Perhaps we will have to recreate the same rules we have for line symbology also for the labels?

Anyway - it would be nice, if the visibility of features in the symbology could somehow be linked with the visibility of the labels ...

I did not have time to test this in depth, though.

**Comment by m-kuhn** [comment]
It seems already to be linked *somehow* as changing the active rules also changes the visible labels.

**Comment by tudorbarascu** [comment]
Good morning, It seems to have been fixed thanks to https://github.com/qgis/QGIS/commit/ea0ce4ec1ede1342795544bf42a1bdd766d66cec

However, I observed that in QGEP, at `749803.7, 264091.9`, the styling doesn't show, but labels do show.
![pic](https://cloud.githubusercontent.com/assets/3179646/10657126/8a4dd46e-788f-11e5-8333-d28a2d9a5129.png)

**Comment by andreasneumann** [comment]
Seems it is not fully fixed. I will provide a small test case to the bug report so Jürgen can more easily test it.

It is always a good idea to also provide a test project, to more efficiently fix these problems.

**Comment by andreasneumann** [comment]
To me it seems like the problem with the ELSE rule is fixed, but there is also a problem with scale ranges that are not fully honored by the labeling engine.

**Comment by andreasneumann** [comment]
hm - still not sure what is really going on - sorry.

I tried to narrow this down to a simpler test case - but then the bug does not show up ...

Tudor - have you found out more about it?

**Comment by tudorbarascu** [comment]
@andreasneumann I have just started to re-look on it, I'll recreate an example with the bug soon.

**Comment by tudorbarascu** [comment]
I have uploaded bug recreation example on the issue page as although you beat me to by opening your example I only found geometryless layers (I probably must have done something wrong).

**Comment by andreasneumann** [comment]
Now it seems to fixed. I tested it with another similar example. See https://github.com/qgis/QGIS/commit/b36cd1f00213be568ab6b86fb10ff63246759935

**Comment by tudorbarascu** [comment]
Indeed it is fixed. However, keep in mind that it's only in master, as although the fixing commit exists in the 2.12 branch, the packages for windows and linux etc. were created before the fix was done, so if anyone uses 2.12 not build from source, he/she will have to wait for 2.12.1

**Comment by andreasneumann** [comment]
Jürgen promised that there will be a 2.12.1 release

There will probably more problems that justify the 2.12.1 release.
