### ISSUE TITLE
QGIS can't open three tables from sample database

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#241]
I'm using https://github.com/QGEP/data/raw/demodata/qgep_demodata.backup 
and qgis fails to open 3 tables :

![image](https://cloud.githubusercontent.com/assets/1629853/19806743/0cc6789e-9d1d-11e6-8ace-ec059cff0713.png)

Moved from https://github.com/QGEP/docs/issues/29

**Comment by sjib** [comment]
I get the same error today with todays demodata.

**Comment by m-kuhn** [comment]
Fixed in the latest model update.

@sjib Please also apply https://github.com/QGEP/datamodel/commit/3eb42bf7ecaea3bfd087762cdec6180d1618a7be to your generator before the next update

**Comment by sjib** [comment]
Where can I find the 3 missing views in the datamodel to add them manually?
vw_qgep_damage
vw_gep_maintenance
vw_qgep_network_segment - seems to be here: https://github.com/QGEP/datamodel/blob/master/07_views_for_network_tracking.sql

![qgis2 18_demodata_qgep_views](https://cloud.githubusercontent.com/assets/1265865/20465697/ed81023e-af63-11e6-9175-a704247361bc.jpg)

**Comment by sjib** [comment]
With vw_qgep_network_segment added there are only two missing views
![qgis2 18_demodata_layer_error4](https://cloud.githubusercontent.com/assets/1265865/20465762/91958c0e-af65-11e6-91a6-2d12cb8b0525.jpg)

**Comment by m-kuhn** [comment]
This is fixed in the latest [demodata](https://github.com/QGEP/data/archive/demodata.zip) as well as the [empty database template](https://github.com/QGEP/datamodel/releases/tag/20161116-131957).

**Comment by sjib** [comment]
vw_qgep_network_segment still not correctly imported (view is here https://github.com/QGEP/datamodel/blob/master/07_views_for_network_tracking.sql)
see also https://github.com/QGEP/docs/issues/29

**Comment by tudorbarascu** [comment]
This view simply needs to be refreshed.
As far as I know, that's how materialized views work.
So, it's correctly imported, but the refresh materialized view needs to be done/documented.

**Comment by m-kuhn** [comment]
I just tried again with the latest demodata dump (from today).
The original problem does not happen here with postgres 9.5.5 and postgis 2.2.
If someone is able to reproduce this with https://github.com/QGEP/data/archive/demodata.zip, please reopen.
